Show number of ready containers
argoproj/argo-cd-ui pull request #37
Opened 2018-09-06 22:19 UTC by merenbach

Shows count of ready containers and closes https://github.com/argoproj/argo-cd/issues/539.

![image](https://user-images.githubusercontent.com/1137108/45188165-2836a900-b1e8-11e8-8d81-40383195290d.png)

2018-09-06 22:27 UTC, alexmt requested changes

2018-09-06 22:27 UTC, alexmt commented on src/app/applications/components/application-resources-tree/application-resources-tree.tsx
> +function countReadyContainerStatuses(containerStatuses) {
Please fix build error:

```
yarn build


ERROR in [at-loader] ./src/app/applications/components/application-resources-tree/application-resources-tree.tsx:33:38
    TS7006: Parameter 'containerStatuses' implicitly has an 'any' type.

ERROR in [at-loader] ./src/app/applications/components/application-resources-tree/application-resources-tree.tsx:35:32
    TS7006: Parameter 'containerStatus' implicitly has an 'any' type.
Child html-webpack-plugin for "index.html":
```

2018-09-06 22:27 UTC, alexmt commented on src/app/applications/components/application-resources-tree/application-resources-tree.tsx
> +                            {kubeState.status && kubeState.status.containerStatuses && (
We already have code which creates labels for pods. It is good to keep code with similar responsibility in one please. Please move your changes to https://github.com/argoproj/argo-cd-ui/blob/f9c39fbc3b2e8c64fe19dd74593d8dcb1e439cc9/src/app/applications/components/application-details/application-details.tsx#L352

2018-09-06 23:10 UTC, merenbach commented
Great calls, @alexmt!  I believe they are now addressed!

2018-09-06 23:27 UTC, alexmt requested changes

2018-09-06 23:27 UTC, alexmt commented on src/app/applications/components/application-details/application-details.tsx
> +            const readyContainers = "" + readyStatuses.length + "/" + allStatuses.length + " containers ready";
Please fix linter warnings:

```
yarn lint                                                                                                                        (tools-sgmnt-prod.cluster.k8s.local/dev-deploy-argocd-us-west-2-prod-cdp)
yarn run v1.6.0
$ tslint -p ./src/app

ERROR: /Users/amatyushentsev/root/argo-cd-ui/src/app/applications/components/application-details/application-details.tsx[368, 37]: " should be '
ERROR: /Users/amatyushentsev/root/argo-cd-ui/src/app/applications/components/application-details/application-details.tsx[368, 65]: " should be '
ERROR: /Users/amatyushentsev/root/argo-cd-ui/src/app/applications/components/application-details/application-details.tsx[368, 92]: " should be '
```

you might use string interpolation:

```
const readyContainers = `${readyStatuses.length}/${allStatuses.length} containers ready`;
```

2018-09-06 23:27 UTC, alexmt commented on src/app/applications/components/application-details/application-details.tsx
> +    state: Map<string, any>;
state is not Map (Map is a class in javascript):


```
interface ContainerStatus {
  state: {[name: string]: any};
}
```

2018-09-07 00:27 UTC, alexmt approved these changes

2018-09-07 15:33 UTC, merged