Implement project role functionality
argoproj/argo-cd-ui pull request #43
Opened 2018-09-12 21:06 UTC by dthomson25

Adds functionality for the following features:
- Creating roles
- Deleting roles
- Changing policies and description
- Still needs to implement the creation and deletion of JWT tokens

2018-09-12 21:07 UTC, dthomson25 commented
This PR addresses the following issue: https://github.com/argoproj/argo-cd/issues/548

2018-09-13 04:00 UTC, alexmt requested changes

2018-09-13 04:00 UTC, alexmt commented on src/app/settings/components/project-details/project-details.tsx
> +                                            role: params.get('newRole') === null ? proj.spec.roles.find((x) => params.get('editRole') === x.name) : undefined,
The `proj.spec.roles` is undefined if project has no roles. Page renderign fails with `Uncaught TypeError: Cannot read property 'find' of undefined`

2018-09-13 04:00 UTC, alexmt commented on src/app/settings/components/project-role-edit-panel/project-role-edit-panel.tsx
> +                    roleName: !params.roleName && 'Project name is required',
This should be `Role name is required`

2018-09-13 04:00 UTC, alexmt commented on src/app/settings/components/project-role-edit-panel/project-role-edit-panel.tsx
> +                                        <i className='fa fa-times' onClick={() => api.setValue('policies', removeEl(api.values.policies, i))}/>
'x' button should have pointer cursor.

2018-09-13 04:00 UTC, alexmt commented on src/app/settings/components/project-role-edit-panel/project-role-edit-panel.tsx
> +                            {(api.values.policies as Array<string>).map((_, i) => (
Looks like policies text boxes and 'x' buttons are not aligned well. Please use layout as project edit panel: https://github.com/argoproj/argo-cd-ui/blob/857ac806ae3ffbdc6eb44957aa08fcd414cea6f1/src/app/settings/components/project-edit-panel/project-edit-panel.tsx#L43

2018-09-13 04:00 UTC, alexmt commented on src/app/settings/components/project-role-edit-panel/project-role-edit-panel.tsx
> +                                <div className='row'>
Each element in array must have key: https://reactjs.org/docs/lists-and-keys.html#keys

2018-09-13 04:00 UTC, alexmt commented on src/app/settings/components/project-role-edit-panel/project-role-edit-panel.tsx
> +                            (api.values.jwtTokens || []).map((jwtToken: models.JwtToken) => (
Each element in array must have key: https://reactjs.org/docs/lists-and-keys.html#keys

2018-09-13 04:00 UTC, alexmt commented on src/app/shared/services/projects-service.ts
> +        for (let i = 0; i < proj.spec.roles.length; i++) {
This fails is project has no roles, since `roles` field is undefined in this case.

2018-09-13 04:00 UTC, alexmt commented on src/app/shared/services/projects-service.ts
> +            updatedSpec.roles = updatedSpec.roles.concat(updatedRole);
This fails is project has no roles, since roles field is undefined in this case.

2018-09-13 04:00 UTC, alexmt commented on src/app/settings/components/project-role-edit-panel/project-role-edit-panel.tsx
> +                        <a onClick={() => api.setValue('policies', (api.values.policies || []).concat(''))}>add source</a>
Instead of asking user to provide policy line by line I would suggest to either just let user type whole policy in text area or provide user friendly UI which generates policy: . 

```
(x) <entity dropdown>     <action dropdown>    [text field]     <allow/deny dropdown>
(x) <applications>        <get>                [*/*]            <allow>
(x) <applications>        <create>             [*/*]            <deny>

(add rule link)
```

I would suggest to use text area in this PR and work on user friendly UI later

2018-09-13 04:00 UTC, alexmt commented on src/app/settings/components/project-role-edit-panel/project-role-edit-panel.tsx
> +                                        <div className='columns small-3'>ISSUEDAT</div>
ISSUED AT

2018-09-13 04:00 UTC, alexmt commented on src/app/settings/components/project-role-edit-panel/project-role-edit-panel.tsx
> +                                        <div className='columns small-3'>EXPIRESAT</div>
EXPIRES AT

2018-09-13 04:00 UTC, alexmt commented on src/app/settings/components/project-role-edit-panel/project-role-edit-panel.tsx
> +                        { api.values.jwtTokens !== null ? (
`api.values.jwtTokens !== null && api.values.jwtTokens.length > 0`

2018-09-13 22:16 UTC, dthomson25 commented on src/app/settings/components/project-role-edit-panel/project-role-edit-panel.tsx
> +                        { api.values.jwtTokens !== null ? (
fixed

2018-09-13 22:17 UTC, dthomson25 commented on src/app/settings/components/project-role-edit-panel/project-role-edit-panel.tsx
> +                                        <div className='columns small-3'>EXPIRESAT</div>
fixed

2018-09-13 22:17 UTC, dthomson25 commented on src/app/settings/components/project-role-edit-panel/project-role-edit-panel.tsx
> +                                        <div className='columns small-3'>ISSUEDAT</div>
fixed

2018-09-13 22:17 UTC, dthomson25 commented on src/app/settings/components/project-role-edit-panel/project-role-edit-panel.tsx
> +                        <a onClick={() => api.setValue('policies', (api.values.policies || []).concat(''))}>add source</a>
replaced with textarea. I'll make another PR to address the user friendly UI after finishing this PR.

2018-09-13 22:17 UTC, dthomson25 commented on src/app/shared/services/projects-service.ts
> +            updatedSpec.roles = updatedSpec.roles.concat(updatedRole);
fixed

2018-09-13 22:17 UTC, dthomson25 commented on src/app/shared/services/projects-service.ts
> +        for (let i = 0; i < proj.spec.roles.length; i++) {
fixed

2018-09-13 22:17 UTC, dthomson25 commented on src/app/settings/components/project-role-edit-panel/project-role-edit-panel.tsx
> +                            (api.values.jwtTokens || []).map((jwtToken: models.JwtToken) => (
fixed

2018-09-13 22:17 UTC, dthomson25 commented on src/app/settings/components/project-role-edit-panel/project-role-edit-panel.tsx
> +                                <div className='row'>
replaced with text area

2018-09-13 22:17 UTC, dthomson25 commented on src/app/settings/components/project-role-edit-panel/project-role-edit-panel.tsx
> +                            {(api.values.policies as Array<string>).map((_, i) => (
Replaced with text area

2018-09-13 22:17 UTC, dthomson25 commented on src/app/settings/components/project-role-edit-panel/project-role-edit-panel.tsx
> +                                        <i className='fa fa-times' onClick={() => api.setValue('policies', removeEl(api.values.policies, i))}/>
Removed due to text area

2018-09-13 22:17 UTC, dthomson25 commented on src/app/settings/components/project-role-edit-panel/project-role-edit-panel.tsx
> +                    roleName: !params.roleName && 'Project name is required',
fixed

2018-09-13 22:17 UTC, dthomson25 commented on src/app/settings/components/project-details/project-details.tsx
> +                                            role: params.get('newRole') === null ? proj.spec.roles.find((x) => params.get('editRole') === x.name) : undefined,
fixed

2018-09-13 23:01 UTC, alexmt requested changes
nice work!

requested few minor comment. Also please fix linter warning and delete empty `project-role-edit-panel.scss` file

2018-09-13 23:01 UTC, alexmt commented on src/app/settings/components/project-role-edit-panel/project-role-edit-panel.tsx
> +// function removeEl(items: any[], index: number) {
Please remove commented code

2018-09-13 23:01 UTC, alexmt commented on src/app/settings/components/project-role-edit-panel/project-role-edit-panel.tsx
> +    constructor(props: ProjectRoleEditPanelProps) {
constructor is not required if it is only calling parent class contstructor.

2018-09-13 23:01 UTC, alexmt commented on src/app/settings/components/project-role-edit-panel/project-role-policies.tsx
> +
Looks like this has to be removed.

2018-09-13 23:01 UTC, alexmt commented on src/app/settings/components/project-details/project-details.tsx
> +                                            {params.get('newRole') === null ? (
There is no space between `Update` and `Delete` buttons.

2018-09-14 16:47 UTC, alexmt approved these changes
LGTM

2018-09-14 16:48 UTC, dthomson25 commented on src/app/settings/components/project-role-edit-panel/project-role-edit-panel.tsx
> +// function removeEl(items: any[], index: number) {
fixed

2018-09-14 16:48 UTC, dthomson25 commented on src/app/settings/components/project-role-edit-panel/project-role-edit-panel.tsx
> +    constructor(props: ProjectRoleEditPanelProps) {
fixed

2018-09-14 16:48 UTC, dthomson25 commented on src/app/settings/components/project-details/project-details.tsx
> +                                            {params.get('newRole') === null ? (
fixed

2018-09-14 16:51 UTC, merged