Show operation without status.operationStatus existing
argoproj/argo-cd-ui pull request #70
Opened 2018-10-31 18:45 UTC by dthomson25

2018-10-31 19:08 UTC, alexmt requested changes
There is no need to introduce `syncing` field in state. 

Then user clicks sync button or requests any other operation it sets `operation` field in application CRD. When controller starts executing operation it moves info about requires operations and progress into  `status.operationState` and null out `operation` field. 

UI should show operation if either `operation` or `status.operationState` is set.

2018-10-31 21:53 UTC, dthomson25 commented
Thanks for the feedback! I pushed a chance that removed the syncing state

2018-11-01 17:05 UTC, alexmt approved these changes
LGTM. Fix one comment before merging

2018-11-01 17:05 UTC, alexmt commented on src/app/applications/components/application-status-panel/application-status-panel.tsx
> +        appOperationState.phase = models.OperationPhases.InProgress;
Looks like this line it not needed

2018-11-01 18:27 UTC, merged