Add progress rollout button to patch rollout
argoproj/argo-cd-ui pull request #89
Opened 2019-01-02 16:37 UTC by dthomson25

2019-02-27 06:48 UTC, alexmt requested changes

2019-02-27 06:48 UTC, alexmt commented on src/app/applications/components/application-details/application-details.tsx
> +        if (resource.kind === 'Rollout') {
Please add `resource.group === 'argoproj.io'`

2019-02-27 06:48 UTC, alexmt commented on src/app/applications/components/rollout-node-info/rollout-node-info.tsx
> +            {props.live.spec.strategy.blueGreen.previewService !== '' && (
I think `props.live.spec.strategy.blueGreen` and `props.live.status` might be null . Please add null checks to avoid NPE

2019-02-28 22:28 UTC, dthomson25 commented
Closing since users can now edit the manifest yaml in the UI, and we should write a more general solution for adding custom actions to UI

2019-02-28 22:28 UTC, closed without merging